// md2form autocomplete suggestions
export const MD2FORM_PROPERTIES = {
  type: [
    'short_text',
    'long_text',
    'email',
    'phone',
    'number',
    'dropdown',
    'radio',
    'checkbox',
    'date',
    'time',
    'rating',
    'likert',
    'matrix',
    'scale',
    'file_upload',
    'signature',
    'boolean',
    'image',
    'video',
    'section_header',
  ],
  required: ['true', 'false'],
  visible: ['true', 'false'],
  placeholder: [],
  maxLength: [],
  default: [],
  options: [],
  allowOther: ['true', 'false'],
  searchable: ['true', 'false'],
  minSelected: [],
  maxSelected: [],
  min: [],
  max: [],
  step: [],
  integerOnly: ['true', 'false'],
  rows: [],
  labels: [],
  minLabel: [],
  maxLabel: [],
  onLabel: [],
  offLabel: [],
  includeTime: ['true', 'false'],
  minDate: [],
  maxDate: [],
  stepMinutes: ['15', '30', '60'],
  scale: ['3', '4', '5', '7', '10'],
  icon: ['star', 'heart', 'thumbs_up', 'circle'],
  scaleLabels: [],
  statements: [],
  requiredPerStatement: ['true', 'false'],
  cellType: ['radio', 'checkbox', 'number', 'short_text'],
  requiredPerRow: ['true', 'false'],
  allowedTypes: ['pdf', 'docx', 'jpg', 'png'],
  maxFiles: ['1', '3', '5', '10'],
  maxSizeMB: ['5', '10', '20', '50'],
  captureMode: ['draw', 'type', 'upload'],
  src: [],
  alt: [],
  width: ['auto'],
  height: ['auto'],
  caption: [],
  title: [],
  subtitle: [],
  minTime: [],
  maxTime: [],
  columns: [],
};

export const PROPERTY_DESCRIPTIONS: Record<string, string> = {
  type: 'Question type',
  required: 'Mark as required field',
  visible: 'Show or hide this field',
  placeholder: 'Placeholder text',
  maxLength: 'Maximum input length',
  default: 'Default field value',
  options: 'Comma-separated options',
  allowOther: 'Allow "other" option',
  searchable: 'Enable dropdown search',
  minSelected: 'Minimum selected options',
  maxSelected: 'Maximum selected options',
  min: 'Minimum value',
  max: 'Maximum value',
  step: 'Step interval for numbers',
  integerOnly: 'Allow integer values only',
  rows: 'Number of rows for textarea',
  labels: 'Pair labels for rating',
  minLabel: 'Label for minimum value',
  maxLabel: 'Label for maximum value',
  onLabel: 'Label for "on" state',
  offLabel: 'Label for "off" state',
  includeTime: 'Include time picker in date',
  minDate: 'Minimum selectable date',
  maxDate: 'Maximum selectable date',
  stepMinutes: 'Time step in minutes',
  scale: 'Rating scale (1-N)',
  icon: 'Rating icon type',
  scaleLabels: 'Scale option labels',
  statements: 'Likert scale statements',
  requiredPerStatement: 'Require each likert statement',
  cellType: 'Matrix cell input type',
  requiredPerRow: 'Require each matrix row',
  allowedTypes: 'Allowed file types',
  maxFiles: 'Maximum number of files',
  maxSizeMB: 'Maximum file size in MB',
  captureMode: 'Signature capture mode',
  src: 'Image/video source URL',
  alt: 'Alternative text',
  width: 'Media width',
  height: 'Media height',
  caption: 'Media caption',
  title: 'Section title',
  subtitle: 'Section subtitle',
  minTime: 'Minimum time',
  maxTime: 'Maximum time',
  columns: 'Matrix column labels',
};

export const TYPE_PROPERTY_TEMPLATES: Record<string, Array<[string, string]>> = {
  short_text: [
    ['placeholder', '"ここに入力してください"'],
    ['required', 'false'],
    ['maxLength', '100'],
  ],
  long_text: [
    ['placeholder', '"詳細を入力してください"'],
    ['rows', '4'],
    ['required', 'false'],
    ['maxLength', '500'],
  ],
  number: [
    ['placeholder', '"0"'],
    ['required', 'false'],
    ['min', '0'],
    ['max', '100'],
    ['step', '1'],
    ['integerOnly', 'false'],
  ],
  email: [
    ['placeholder', '"example@example.com"'],
    ['required', 'false'],
  ],
  phone: [
    ['placeholder', '"090-1234-5678"'],
    ['required', 'false'],
  ],
  dropdown: [
    ['options', '"選択肢1","選択肢2","選択肢3"'],
    ['required', 'false'],
    ['searchable', 'false'],
    ['allowOther', 'false'],
  ],
  radio: [
    ['options', '"選択肢1","選択肢2","選択肢3"'],
    ['required', 'false'],
    ['allowOther', 'false'],
  ],
  checkbox: [
    ['options', '"選択肢1","選択肢2","選択肢3"'],
    ['required', 'false'],
    ['minSelected', '1'],
    ['maxSelected', '3'],
  ],
  date: [
    ['required', 'false'],
    ['includeTime', 'false'],
    ['minDate', '"2025-01-01"'],
    ['maxDate', '"2030-12-31"'],
  ],
  time: [
    ['required', 'false'],
    ['minTime', '"09:00"'],
    ['maxTime', '"18:00"'],
    ['stepMinutes', '15'],
  ],
  rating: [
    ['required', 'false'],
    ['scale', '5'],
    ['labels', '"低い","高い"'],
    ['icon', 'star'],
  ],
  likert: [
    ['required', 'false'],
    ['statements', '"項目1","項目2","項目3"'],
    ['scaleLabels', '"全くそう思わない","そう思わない","普通","そう思う","とてもそう思う"'],
    ['requiredPerStatement', 'false'],
  ],
  matrix: [
    ['required', 'false'],
    ['rows', '"行1","行2","行3"'],
    ['columns', '"列1","列2","列3"'],
    ['cellType', 'radio'],
    ['requiredPerRow', 'false'],
  ],
  scale: [
    ['required', 'false'],
    ['min', '1'],
    ['max', '5'],
    ['step', '1'],
    ['minLabel', '"低い"'],
    ['maxLabel', '"高い"'],
  ],
  file_upload: [
    ['required', 'false'],
    ['allowedTypes', '"pdf","docx","jpg","png"'],
    ['maxFiles', '1'],
    ['maxSizeMB', '10'],
  ],
  signature: [
    ['required', 'false'],
    ['captureMode', 'draw'],
  ],
  image: [
    ['src', '"https://example.com/image.jpg"'],
    ['alt', '"画像の説明"'],
    ['width', 'auto'],
    ['height', 'auto'],
    ['caption', '""'],
  ],
  video: [
    ['src', '"https://example.com/video.mp4"'],
    ['width', 'auto'],
    ['height', 'auto'],
    ['caption', '""'],
  ],
  boolean: [
    ['required', 'false'],
    ['onLabel', '"はい"'],
    ['offLabel', '"いいえ"'],
  ],
  section_header: [
    ['title', '"セクションタイトル"'],
    ['subtitle', '"補足説明"'],
  ],
};
